# Site settings
title: UTD Event Data
description: > # this means to ignore newlines until "baseurl:"
 and submit a pull request.  
url: Jingnan92.github.io
baseurl: /UTDEventData
future: true

# Build settings
markdown: kramdown

# Other options
#permalink: blog/:year/:month/:title
#job.title: "Assistant Professor"
#excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
